version: 0.2
env: 
  secret-manager:
      TOKEN: firstSecret:tokenForSonar

phases:
  install:
    runtime-versions:
      java: latest
  build:
    commands:
      - mvn verify sonar:sonar -Dsonar.projectKey=java-project-aws1 -Dsonar.organization=java-project-aws1 -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=fcd5cfcb3d4ad91d039f019c2a3831017ca03762
